// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEF.Data.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public DateTime? Fecha { get; set; }

    public int? IdFormaPago { get; set; }

    public string Cliente { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual FormasPago IdFormaPagoNavigation { get; set; }
}