// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ApiEF.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ApiEF.Data.Models
{
    public partial interface IPractica01DbContextProcedures
    {
        Task<int> sp_AGREGAR_DETALLEAsync(int? id_factura, int? id_articulo, int? cantidad, decimal? precio_vendido, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_EDITAR_ARTICULOSAsync(int? id, string nombre, decimal? precio_unitario, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ElIMINAR_ARTICULOSAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_GUARDAR_ARTICULOSAsync(string nombre, decimal? precio_unitario, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_INSERTAR_MAESTRO_FACTURASAsync(int? id_forma_pago, string cliente, OutputParameter<int?> id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_ARTICULOSResult>> SP_RECUPERAR_ARTICULOSAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_ARTICULOS_POR_IDResult>> SP_RECUPERAR_ARTICULOS_POR_IDAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_FACTURASResult>> SP_RECUPERAR_FACTURASAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_FACTURAS_POR_IDResult>> SP_RECUPERAR_FACTURAS_POR_IDAsync(int? nro_factura, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
