// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiEF.Data.Models
{
    public partial class SP_RECUPERAR_FACTURAS_POR_IDResult
    {
        public int nro_Factura { get; set; }
        public DateTime? fecha { get; set; }
        [StringLength(50)]
        public string cliente { get; set; }
        [StringLength(30)]
        public string articulo { get; set; }
        [Column("precio_vendido", TypeName = "decimal(10,2)")]
        public decimal? precio_vendido { get; set; }
        public int? cantidad { get; set; }
        [StringLength(50)]
        public string forma_pago { get; set; }
    }
}
