// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiEF.Data.Models
{
    public partial class SP_RECUPERAR_ARTICULOSResult
    {
        public int id { get; set; }
        [StringLength(30)]
        public string nombre { get; set; }
        [Column("precio_Unitario", TypeName = "decimal(10,2)")]
        public decimal? precio_Unitario { get; set; }
        public bool? esta_activo { get; set; }
    }
}
